# android/Gemfile
source "https://rubygems.org"

gem "fastlane", "~> 2.217.0"
gem "bundler", "~> 2.4.0"

# Plugins
plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
