# ios/Gemfile  
source "https://rubygems.org"

gem "fastlane", ">= 2.227.2"
gem "bundler", ">= 2.3.0"          # 👈 เปลี่ยนจาก ~> 2.4.0 เป็น >= 2.4.0
gem "cocoapods", "~> 1.15"
gem "abbrev"

# Plugins
plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
