# .github/workflows/android-reusable.yml - FIXED & SIMPLIFIED
name: Android Build & Deploy

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      version_code:
        required: true
        type: string
      branch:
        required: true
        type: string
      environment:
        required: false
        type: string
        default: 'development'
    secrets:
      KEYSTORE_FILE:
        required: true
      KEYSTORE_PASSWORD:
        required: true
      KEY_ALIAS:
        required: true
      KEY_PASSWORD:
        required: true
      GOOGLE_PLAY_JSON_KEY:
        required: true
  
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (e.g., 1.2.3)'
        required: true
        default: '1.0.0'
      version_code:
        description: 'Version code (e.g., 123)'
        required: true
        default: '1'
      branch:
        description: 'Branch name'
        required: true
        default: 'develop'
      environment:
        description: 'Environment'
        required: false
        default: 'development'

env:
  FLUTTER_VERSION: '3.32.2'

jobs:
  build-and-deploy-android:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    
    steps:
      #ดึงโค้ดใน git มาประมวลผล 
      - name: Checkout
        uses: actions/checkout@v4

      #ติดตั้ง Flutter SDK ใน GitHub runner
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      #ติดตั้ง java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      #เก็บ dependencies ที่ดาวน์โหลดแล้วไว้ใช้ซ้ำ
      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.PUB_CACHE }}
            ~/.gradle/wrapper
            ~/.gradle/caches
          key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      #ติดตั้ง packages ที่ต้องใช้ในโปรเจกต์
      - name: Get Dependencies
        run: |
          echo "📦 Installing dependencies..."
          flutter pub get

      #อัพเดทเลขเวอร์ชันของแอป
      - name: Update Version
        run: |
          echo "📝 Updating version to: ${{ inputs.version }}+${{ inputs.version_code }}"
          sed -i "s/^version: .*/version: ${{ inputs.version }}+${{ inputs.version_code }}/" pubspec.yaml
          grep "^version:" pubspec.yaml

      #ตั้งค่่า Keystore
      - name: Setup Android Keystore
        run: |
          echo "🔑 Setting up Android keystore..."
          
          # Create keystore from base64
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > android/app/key.jks
          
          # Verify keystore exists
          if [ ! -f "android/app/key.jks" ]; then
            echo "❌ Failed to create keystore"
            exit 1
          fi
          
          # Create key.properties
          cat > android/key.properties << EOF
          storeFile=key.jks
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          EOF
          
          echo "✅ Keystore setup completed"
          ls -la android/app/key.jks

      #สร้างไฟล์ aab
      - name: Build Android AAB
        run: |
          echo "🔨 Building Android App Bundle..."
          
          flutter build appbundle --release \
            --build-name="${{ inputs.version }}" \
            --build-number="${{ inputs.version_code }}"
          
          # Simple verification
          if [ -f "build/app/outputs/bundle/release/app-release.aab" ]; then
            echo "✅ AAB built successfully"
            ls -lh build/app/outputs/bundle/release/app-release.aab
          else
            echo "❌ AAB build failed"
            exit 1
          fi

      #เตรียม Ruby environment เพื่อใช้งาน Fastlane
      - name: Setup Ruby and Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          working-directory: android

      #อัพไฟล์ขึ้น Google Play
      - name: Deploy to Google Play
        run: |
          echo "🚀 Deploying to Google Play..."
          
          # 🔍 DEBUG: ตรวจสอบ AAB file
          echo "🔍 Searching for AAB files..."
          find . -name "*.aab" -type f
          find . -path "*/outputs/bundle/*" -type f
          
          # Check expected location
          if [ -f "build/app/outputs/bundle/release/app-release.aab" ]; then
            echo "✅ AAB found at expected location"
            ls -lh build/app/outputs/bundle/release/app-release.aab
          else
            echo "❌ AAB not found at expected location"
            echo "📂 Checking build directory structure..."
            ls -la build/ || echo "No build directory"
            ls -la build/app/ || echo "No build/app directory"  
            ls -la build/app/outputs/ || echo "No outputs directory"
          fi
          
          # Setup Google Play credentials
          echo "${{ secrets.GOOGLE_PLAY_JSON_KEY }}" | base64 -d > android/google-play-key.json
          
          # Determine track and deployment lane
          case "${{ inputs.branch }}" in
            "master") 
              TRACK="production"
              LANE="deploy_master"
              ;;
            "preprod") 
              TRACK="alpha"
              LANE="deploy_preprod"
              ;;
            *) 
              TRACK="internal"
              LANE="deploy_develop"
              ;;
          esac
          
          echo "📤 Deploying to track: $TRACK"
          echo "🎯 Using lane: $LANE"
          
          # Deploy with Fastlane (only if AAB exists)
          if [ -f "build/app/outputs/bundle/release/app-release.aab" ]; then
            cd android
            bundle exec fastlane $LANE
            echo "✅ Deployment completed!"
          else
            echo "❌ Cannot deploy: AAB file missing"
            exit 1
          fi

      #เก็บไฟล์ build results ไว้ใน GitHub สำหรับ download หรือ debug
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-${{ inputs.version }}-${{ github.run_number }}
          path: |
            build/app/outputs/bundle/release/*.aab
            android/fastlane/logs/
          retention-days: 30

      #สรุปผลการ build 
      - name: Build Summary
        run: |
          echo "## 🤖 Android Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Version:** ${{ inputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Version Code:** ${{ inputs.version_code }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch:** ${{ inputs.branch }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Environment:** ${{ inputs.environment }}" >> $GITHUB_STEP_SUMMARY
          
          if [ -f "build/app/outputs/bundle/release/app-release.aab" ]; then
            size=$(ls -lh build/app/outputs/bundle/release/app-release.aab | awk '{print $5}')
            echo "- **AAB Size:** $size" >> $GITHUB_STEP_SUMMARY
          fi
          
          echo "- **Status:** ✅ Success" >> $GITHUB_STEP_SUMMARY

      #ลบไฟล์ที่มีข้อมูลลับ หลังจาก build/deploy เสร็จสิ้น
      - name: Cleanup
        if: always()
        run: |
          rm -f android/app/key.jks
          rm -f android/key.properties  
          rm -f android/google-play-key.json